import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { Layout, Navbar, Table } from "~/components";
import { defaultDateDisplay, isEmpty } from "~/lib/helpers";
import { BASE_URL } from "~/lib/setupApi";
import { fetchListOffer } from "./api/api";
import styles from "./ListOffer.module.scss";

function ListOfferPage() {
  const [listOffer, setListOffer] = useState([]);
  const router = useRouter();
  const { id } = router.query;

  const setNewData = async () => {
    if (!isEmpty(id)) {
      const response = await fetchListOffer(id as string);
      if (response.state) {
        setListOffer(response.data);
      }
    }
  };

  useEffect(() => {
    setNewData();
  }, []);

  return (
    <>
      <Head>
        <title>List Offer | Lofiators</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout classNames={styles.ListOfferPage}>
        <Navbar />

        <section className={styles.ListOfferPage}>
          <h3 className='font-semibold text-xl'>Detail Penawaran Anda</h3>

          <div className='mt-5 bg-white p-5 shadow-md rounded-sm'>
            <table width={"100%"}>
              <tbody>
                <tr>
                  <td width={"20%"} className='text-gray-500 pb-4'>
                    Judul
                  </td>
                  <td>:</td>
                  <td width={"70%"}>{listOffer?.service?.name}</td>
                </tr>
                <tr>
                  <td width={"20%"} className='text-gray-500 pb-4'>
                    Deskripsi
                  </td>
                  <td>:</td>
                  <td width={"70%"}>{listOffer?.service?.description}</td>
                </tr>
                <tr>
                  <td width={"20%"} className='text-gray-500 pb-4'>
                    Budget
                  </td>
                  <td>:</td>
                  <td width={"70%"}>
                    {listOffer?.service?.min_budget} -{" "}
                    {listOffer?.service?.max_budget} /{" "}
                    {listOffer?.service?.weight}
                  </td>
                </tr>
                <tr>
                  <td width={"20%"} className='text-gray-500 pb-4'>
                    Publish Date
                  </td>
                  <td>:</td>
                  <td width={"70%"}>
                    {defaultDateDisplay(
                      listOffer?.service?.publish_date,
                      false
                    )}
                  </td>
                </tr>
                <tr>
                  <td width={"20%"} className='text-gray-500 pb-4'>
                    Deadline
                  </td>
                  <td>:</td>
                  <td width={"70%"}>
                    {defaultDateDisplay(
                      listOffer?.service?.publish_limit,
                      false
                    )}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <h3 className='font-semibold text-xl my-5'>Tawaran yang masuk</h3>

          <Table
            headers={[
              {
                label: "No.",
                width: "5%",
              },
              {
                label: "Nama",
              },
              {
                label: "Image",
              },
              {
                label: "Kota",
              },
              {
                label: "Email",
              },
              {
                label: "No HP",
              },
              {
                label: "Letter",
                width: "300px",
              },
            ]}>
            {listOffer?.service_offers?.map((item, index: number) => {
              return (
                <tr className='bg-white border-b'>
                  <td className='px-6 py-4'>{index + 1}</td>
                  <td className='px-6 py-4'>{item.user_name}</td>
                  <td className='px-6 py-4'>
                    <img
                      src={`${BASE_URL}/${item.image}`}
                      alt={item.user_name}
                      className='max-w-sm'
                      style={{
                        width: "50px",
                      }}
                    />
                  </td>
                  <td className='px-6 py-4'>{item.city}</td>
                  <td className='px-6 py-4'>{item.email}</td>
                  <td className='px-6 py-4'>{item.no_hp}</td>
                  <td className='px-6 py-4'>{item.letter}</td>
                </tr>
              );
            })}
          </Table>
        </section>
      </Layout>
    </>
  );
}

export default ListOfferPage;
