import Head from "next/head";
import React from "react";
import { Layout, Navbar } from "~/components";
import DefaultButton from "~/components/button/DefaultButton";
import OtherOffer from "~/layouts/find-culvitator/detail/OtherOffer";
import styles from "./DetailFindProducer.module.scss";

function DetailFindProducerPage() {
  return (
    <>
      <Head>
        <title>Temukan Supplier | Lofiators</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout classNames={styles.DetailFindProducerPage}>
        <Navbar />

        <section className={styles.DetailFindProducerPageContent}>
          <div className={styles.DetailFindProducerPageCardOffer}>
            <div className='bg-white p-4'>
              <div>
                <h5 className='text-lg'>
                  Saya menyediakan ikan bandeng segar, skala kecil dan besar
                </h5>
                <span className='text-xs text-gray-300'>4 days ago</span>
              </div>

              <div className='bg-gray-200 h-60 w-11/12 mt-5'></div>

              <p className='text-gray-500 mt-5 text-sm w-10/12'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Id
                mollitia quisquam magni assumenda voluptatem expedita, amet
                reiciendis non laborum asperiores consectetur ea odit omnis
                dolorem officia possimus! Repellat doloremque nemo porro,
                quibusdam nam sapiente iure maiores vitae. Laboriosam voluptates
                exercitationem eos dolor. Fuga ipsam reprehenderit reiciendis
                aliquam voluptatem, soluta quidem?
              </p>

              <table className={`${styles.CardItemOfferTable} mt-5 md:w-6/12`}>
                <tbody>
                  <tr>
                    <td className='text-gray-700 font-semibold'>Waktu Panen</td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>Juni, Maret</td>
                  </tr>
                  <tr>
                    <td className='text-gray-700 font-semibold'>
                      Jenis Budidaya
                    </td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>Mujair, Bandeng</td>
                  </tr>
                </tbody>
              </table>

              <DefaultButton
                label='Hubungi'
                className='w-full block bg-green-700 mt-5'
              />
            </div>

            <div className='bg-white p-4 mt-5'>
              <p className='font-medium'>Tentang User</p>

              <div className='mt-5'>
                <div className='flex gap-3 items-center'>
                  <div className='rounded-full bg-gray-300 h-16 w-16'></div>
                  <div>
                    <p className='text-sm'>Wisnu Pratama</p>
                    <p
                      className='text-gray-400 text-sm'
                      style={{
                        fontWeight: "300",
                      }}>
                      085700924165
                    </p>
                  </div>
                </div>

                <div className='mt-5'>
                  <table
                    className={`w-6/12 ${styles.DetailFindProducerPageTableUser}`}>
                    <tbody>
                      <tr>
                        <td className='text-gray-400'>Asal</td>
                        <td className='text-gray-400'>Terdaftar Sejak</td>
                      </tr>
                      <tr>
                        <td className='text-gray-600'>Brebes</td>
                        <td className='text-gray-600'>
                          Selasa, 27 Januari 2020
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>

                <div className='my-4 w-full border-b'></div>
                <p
                  className='text-sm text-gray-500'
                  style={{
                    fontWeight: "300",
                  }}>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Blanditiis recusandae facere et rerum? Corrupti aperiam labore
                  totam esse est molestias eveniet at alias impedit quos sint
                  aliquid, in, incidunt aut sequi. A vero, saepe esse molestias
                  dolore commodi dolor voluptatibus.
                </p>
              </div>
            </div>
          </div>

          <div>
            <OtherOffer />
          </div>
        </section>
      </Layout>
    </>
  );
}

export default DetailFindProducerPage;
