import Head from "next/head";
import React from "react";
import { Layout, Navbar } from "~/components";
import DefaultButton from "~/components/button/DefaultButton";
import OtherOffer from "~/layouts/find-culvitator/detail/OtherOffer";
import { differentDayWithNow, toDayIndo } from "~/lib/helpers";
import { BASE_URL } from "~/lib/setupApi";
import { IFeedDetailModel } from "../utils/types";
import styles from "./DetailFindProducer.module.scss";
import moment from "moment";

interface IPropsDetailFindProducerPage {
  producerDetail: IFeedDetailModel;
}

function DetailFindProducerPage({
  producerDetail,
}: IPropsDetailFindProducerPage) {
  return (
    <>
      <Head>
        <title>Temukan Supplier | Lofiators</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout classNames={styles.DetailFindProducerPage}>
        <Navbar />

        <section className={styles.DetailFindProducerPageContent}>
          <div className={styles.DetailFindProducerPageCardOffer}>
            <div className='bg-white p-4'>
              <div>
                <h5 className='text-lg'>{producerDetail.feed.title}</h5>
                <span className='text-xs text-gray-300'>
                  {differentDayWithNow(producerDetail.user.created_at)}
                </span>
              </div>

              <div className='bg-gray-200 h-60 w-11/12 mt-5'></div>

              <p className='text-gray-500 mt-5 text-sm w-10/12'>
                {producerDetail.feed.description}
              </p>

              <table className={`${styles.CardItemOfferTable} mt-5 md:w-6/12`}>
                <tbody>
                  <tr>
                    <td className='text-gray-700 font-semibold'>Waktu Panen</td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>
                      {producerDetail.feed.harvest_time}
                    </td>
                  </tr>
                  <tr>
                    <td className='text-gray-700 font-semibold'>
                      Jenis Budidaya
                    </td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>
                      {producerDetail.feed.type_cultivation}
                    </td>
                  </tr>
                </tbody>
              </table>

              <DefaultButton
                label='Hubungi'
                className='w-full block bg-green-700 mt-5'
              />
            </div>

            <div className='bg-white p-4 mt-5'>
              <p className='font-medium'>Tentang User</p>

              <div className='mt-5'>
                <div className='flex gap-3 items-center'>
                  <div className='rounded-full bg-gray-300'>
                    <img
                      src={`${BASE_URL}/${producerDetail.user.image}`}
                      alt={`Profile User ${producerDetail.user.name}`}
                      className='rounded-full h-20 w-20'
                    />
                  </div>
                  <div>
                    <p className='text-sm'>{producerDetail.user.name}</p>
                    <p
                      className='text-gray-400 text-sm'
                      style={{
                        fontWeight: "300",
                      }}>
                      {producerDetail.user.no_hp}
                    </p>
                  </div>
                </div>

                <div className='mt-5'>
                  <table
                    className={`w-6/12 ${styles.DetailFindProducerPageTableUser}`}>
                    <tbody>
                      <tr>
                        <td className='text-gray-400'>Asal</td>
                        <td className='text-gray-400'>Terdaftar Sejak</td>
                      </tr>
                      <tr>
                        <td className='text-gray-600'>
                          {producerDetail.user.city}
                        </td>
                        <td className='text-gray-600'>
                          {toDayIndo(
                            moment(producerDetail.user.created_at)
                              .local()
                              .format("dddd")
                          )}
                          ,{" "}
                          {moment(producerDetail.user.created_at).format(
                            "DD MMMM YYYY"
                          )}
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </div>

                <div className='my-4 w-full border-b'></div>
                <p
                  className='text-sm text-gray-500'
                  style={{
                    fontWeight: "300",
                  }}>
                  {producerDetail.user.description}
                </p>
              </div>
            </div>
          </div>

          <div>
            <OtherOffer />
          </div>
        </section>
      </Layout>
    </>
  );
}

export default DetailFindProducerPage;
