import React from "react";
import { Layout, Navbar } from "~/components";
import Head from "next/head";
import { ClickHere } from "../login/LoginPage";
import styles from "./RegisterPage.module.scss";
import DefaultButton from "~/components/button/DefaultButton";
import DefaultInputText from "~/components/input/DefaultInputText";

function RegisterPage() {
  return (
    <>
      <Head>
        <title>Register | Lofiators</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <Layout>
        <section className={styles.registerPage}>
          <div className='md:w-2/4 w-full md:px-0 px-4'>
            <h4 className='title-auth'>Register</h4>

            <div className='mt-4'>
              <DefaultInputText
                label='Nama Lengkap'
                id='name'
                type='text'
                placeholder='Nama Lengkap'
              />
              <DefaultInputText
                label='Email'
                id='email'
                type='email'
                placeholder='user@mail.com'
              />

              <DefaultInputText
                label='Password'
                id='password'
                type='password'
                placeholder='*******'
              />
              <DefaultInputText
                label='Konfirmasi Password'
                id='konfirmasi-password'
                type='password'
                placeholder='*******'
              />
            </div>

            <div className='mt-6'>
              <DefaultButton
                label='Daftar'
                className='block w-full py-2 bg-green-700 text-base'
              />
              <p className='text-xs text-gray-400 mt-3 font-light'>
                Dengan melanjutkan, Anda memahami dan menyetujui penggunaan Kami
                atas informasi yang Anda sampaikan sesuai dengan ketentuan
                Kebijakan Privasi.
              </p>
            </div>

            <ClickHere label='Sudah punya akun?' href='/login' />
          </div>
        </section>
      </Layout>
    </>
  );
}

export default RegisterPage;
