import Head from "next/head";
import React from "react";
import { Layout, Navbar } from "~/components";
import DefaultButton from "~/components/button/DefaultButton";
import styles from "./DetailFindCulvitator.module.scss";
import OtherOffer from "./OtherOffer";

function DetailFindCulvitatorPage() {
  return (
    <>
      <Head>
        <title>Temukan Supplier | Lofiators</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout classNames={styles.DetailFindCulvitatorPage}>
        <Navbar />

        <section className={styles.DetailFindCulvitatorPageContent}>
          <div>
            <OtherOffer />
          </div>

          <div className={styles.DetailFindCulvitatorCardOffer}>
            <div className='bg-white p-4'>
              <div>
                <h5 className='text-lg'>
                  Saya membutuhkan ikan bandeng sebanyak 3 ton, pada bulan
                  Januari.
                </h5>
                <span className='text-xs text-gray-300'>4 days ago</span>
              </div>

              <p className='text-gray-500 mt-5 text-sm w-10/12'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Id
                mollitia quisquam magni assumenda voluptatem expedita, amet
                reiciendis non laborum asperiores consectetur ea odit omnis
                dolorem officia possimus! Repellat doloremque nemo porro,
                quibusdam nam sapiente iure maiores vitae. Laboriosam voluptates
                exercitationem eos dolor. Fuga ipsam reprehenderit reiciendis
                aliquam voluptatem, soluta quidem?
              </p>

              <table className={`${styles.CardItemOfferTable} mt-5 md:w-10/12`}>
                <tbody>
                  <tr>
                    <td className='text-gray-700 font-semibold'>
                      Published Date
                    </td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>18/09/2021 12:15:22</td>

                    <td className='text-gray-700 font-semibold'>
                      Total Tawaran
                    </td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>3</td>
                  </tr>
                  <tr>
                    <td className='text-gray-700 font-semibold'>
                      Published Budget
                    </td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>Rp. 16.000 - 20.000 /Kg</td>

                    <td className='text-gray-700 font-semibold'>Status</td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>
                      <div
                        className='text-white rounded-sm py-1 text-center'
                        style={{
                          backgroundColor: "#40B8DE",
                        }}>
                        Published
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td className='text-gray-700 font-semibold'>Deadline</td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>18/09/2021 12:15:22</td>
                  </tr>
                </tbody>
              </table>

              <div className='mt-8 flex justify-between items-center'>
                <div className='flex gap-3 items-center'>
                  <div className='bg-gray-300 h-16 w-16'></div>
                  <div>
                    <p className='text-sm font-medium text-gray-800'>
                      Wisnu Pratama
                    </p>
                    <p className='text-xs font-light text-gray-500 mt-1'>
                      Surabaya
                    </p>
                    <p className='text-xs font-light text-gray-500 mt-1'>
                      Tawaran ke-10
                    </p>
                  </div>
                </div>

                <div>
                  <DefaultButton
                    label='Ajukan Tawaran'
                    className='mx-2 bg-green-700'
                  />
                  <DefaultButton
                    label='Hubungi Owner'
                    className='bg-green-700'
                  />
                </div>
              </div>
            </div>

            <div className='bg-white mt-5 p-4'>
              <p className='text-base text-gray-700'>
                User yang sudah melakukan penawaran
              </p>
              <div className={styles.DetailFindCulvitatorUserOffer}>
                <div className='flex gap-3 items-center'>
                  <div className='bg-gray-300 h-16 w-16'></div>
                  <div>
                    <p className='text-sm font-medium text-gray-800'>
                      Wisnu Pratama
                    </p>
                    <p className='text-xs font-light text-gray-500 mt-1'>
                      Surabaya
                    </p>
                  </div>
                </div>
                <div className='flex gap-3 items-center'>
                  <div className='bg-gray-300 h-16 w-16'></div>
                  <div>
                    <p className='text-sm font-medium text-gray-800'>
                      Wisnu Pratama
                    </p>
                    <p className='text-xs font-light text-gray-500 mt-1'>
                      Surabaya
                    </p>
                  </div>
                </div>
                <div className='flex gap-3 items-center'>
                  <div className='bg-gray-300 h-16 w-16'></div>
                  <div>
                    <p className='text-sm font-medium text-gray-800'>
                      Wisnu Pratama
                    </p>
                    <p className='text-xs font-light text-gray-500 mt-1'>
                      Surabaya
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
}

export default DetailFindCulvitatorPage;
