import Head from "next/head";
import React from "react";
import { Layout, Navbar } from "~/components";
import DefaultButton from "~/components/button/DefaultButton";
import { defaultDateDisplay, differentDayWithNow } from "~/lib/helpers";
import { BASE_URL } from "~/lib/setupApi";
import { IServiceDetailModel } from "../utils/types";
import styles from "./DetailFindCulvitator.module.scss";
import OtherOffer from "./OtherOffer";

interface IPropsDetailFindCulvitatorPage {
  serviceDetail: IServiceDetailModel;
}

function DetailFindCulvitatorPage({
  serviceDetail,
}: IPropsDetailFindCulvitatorPage) {
  console.log(serviceDetail);
  return (
    <>
      <Head>
        <title>Temukan Supplier | Lofiators</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout classNames={styles.DetailFindCulvitatorPage}>
        <Navbar />

        <section className={styles.DetailFindCulvitatorPageContent}>
          <div>
            <OtherOffer />
          </div>

          <div className={styles.DetailFindCulvitatorCardOffer}>
            <div className='bg-white p-4'>
              <div>
                <h5 className='text-lg'>{serviceDetail?.service.name}</h5>
                <span className='text-xs text-gray-300'>
                  {differentDayWithNow(serviceDetail?.service.publish_date)}
                </span>
              </div>

              <p className='text-gray-500 mt-5 text-sm w-10/12'>
                {serviceDetail?.service.description}
              </p>

              <table className={`${styles.CardItemOfferTable} mt-5 md:w-10/12`}>
                <tbody>
                  <tr>
                    <td className='text-gray-700 font-semibold'>
                      Published Date
                    </td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>
                      {defaultDateDisplay(
                        serviceDetail.service.publish_date,
                        false
                      )}
                    </td>

                    <td className='text-gray-700 font-semibold'>
                      Total Tawaran
                    </td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>
                      {serviceDetail?.service.total_penawaran}
                    </td>
                  </tr>
                  <tr>
                    <td className='text-gray-700 font-semibold'>
                      Published Budget
                    </td>
                    <td width={"5%"}></td>

                    <td className='text-gray-500'>
                      {serviceDetail?.service.min_budget} -{" "}
                      {serviceDetail?.service.max_budget} /
                      {serviceDetail?.service.weight}
                    </td>

                    <td className='text-gray-700 font-semibold'>Status</td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>
                      <div
                        className='text-white rounded-sm py-1 text-center'
                        style={{
                          backgroundColor: "#40B8DE",
                        }}>
                        {serviceDetail?.service.status.toUpperCase()}
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td className='text-gray-700 font-semibold'>Deadline</td>
                    <td width={"5%"}></td>
                    <td className='text-gray-500'>
                      {serviceDetail?.service.publish_limit}
                    </td>
                  </tr>
                </tbody>
              </table>

              <div className='mt-8 flex justify-between items-center'>
                <div className='flex gap-3 items-center'>
                  <div className=' h-16 w-16'>
                    <img
                      src={`${BASE_URL}/${serviceDetail.service.image}`}
                      alt={`Profile User ${serviceDetail.service.user_name}`}
                      className='max-h-16'
                    />
                  </div>
                  <div>
                    <p className='text-sm font-medium text-gray-800'>
                      {serviceDetail?.service.user_name}
                    </p>
                    <p className='text-xs font-light text-gray-500 mt-1'>
                      {serviceDetail?.service.city}
                    </p>
                    <p className='text-xs font-light text-gray-500 mt-1'>
                      Tawaran ke-{serviceDetail?.service.serviceAt}
                    </p>
                  </div>
                </div>

                <div>
                  <DefaultButton
                    label='Ajukan Tawaran'
                    className='mx-2 bg-green-700'
                  />
                  <DefaultButton
                    label='Hubungi Owner'
                    className='bg-green-700'
                  />
                </div>
              </div>
            </div>

            <div className='bg-white mt-5 p-4'>
              <p className='text-base text-gray-700'>
                User yang sudah melakukan penawaran
              </p>
              <div className={styles.DetailFindCulvitatorUserOffer}>
                {serviceDetail.service_offers.map((serviceOffer, index) => {
                  return (
                    <div className='flex gap-3 items-center' key={index}>
                      <div className='bg-gray-300 h-16 w-16'>
                        <img
                          src={`${BASE_URL}/${serviceOffer.image}`}
                          alt={`Profile User Tawar ${serviceOffer.name}`}
                          className='max-h-16'
                        />
                      </div>
                      <div>
                        <p className='text-sm font-medium text-gray-800'>
                          {serviceOffer.name}
                        </p>
                        <p className='text-xs font-light text-gray-500 mt-1'>
                          {serviceOffer.city}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>

              {serviceDetail.service_offers.length === 0 && (
                <p className='text-center text-sm'>Jadilah penawar pertama!</p>
              )}
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
}

export default DetailFindCulvitatorPage;
