import Head from "next/head";
import React from "react";
import { Layout, Navbar } from "~/components";
import Filter from "~/components/filters/Filter";
import CardItemPriducer from "./CardItemProducer";
import styles from "./FindProducer.module.scss";

export interface IProducerItemsList {
  title: string;
  desc: string;
  user: string;
  waktu_panen: string;
  jenis_budidaya: string;
}

const producerItemLists: IProducerItemsList[] = [
  {
    title: "Saya menyediakan ikan bandeng segar, skala kecil dan besar",
    desc: "Saya merupakan pembudidaya ikan bandeng di desa prapag kidul kecamatan Losari Kabupaten Brebes. Untuk melihat lebih jauh silahkan datang ke lokasi saya",
    user: "Wisnu Pratama",
    waktu_panen: "Maret, Juli",
    jenis_budidaya: "Bandeng, Mujair, Gurame",
  },
  {
    title: "Saya menyediakan ikan bandeng segar, skala kecil dan besar",
    desc: "Saya merupakan pembudidaya ikan bandeng di desa prapag kidul kecamatan Losari Kabupaten Brebes. Untuk melihat lebih jauh silahkan datang ke lokasi saya",
    user: "Wisnu Pratama",
    waktu_panen: "Maret, Juli",
    jenis_budidaya: "Bandeng, Mujair, Gurame",
  },
  {
    title: "Saya menyediakan ikan bandeng segar, skala kecil dan besar",
    desc: "Saya merupakan pembudidaya ikan bandeng di desa prapag kidul kecamatan Losari Kabupaten Brebes. Untuk melihat lebih jauh silahkan datang ke lokasi saya",
    user: "Wisnu Pratama",
    waktu_panen: "Maret, Juli",
    jenis_budidaya: "Bandeng, Mujair, Gurame",
  },
  {
    title: "Saya menyediakan ikan bandeng segar, skala kecil dan besar",
    desc: "Saya merupakan pembudidaya ikan bandeng di desa prapag kidul kecamatan Losari Kabupaten Brebes. Untuk melihat lebih jauh silahkan datang ke lokasi saya",
    user: "Wisnu Pratama",
    waktu_panen: "Maret, Juli",
    jenis_budidaya: "Bandeng, Mujair, Gurame",
  },
];

function FindProducerPage() {
  return (
    <>
      <>
        <Head>
          <title>Temukan Produsen | Lofiators</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <Layout classNames={styles.FindProducerPage}>
          <Navbar />

          <section className={styles.FindProducerPageContent}>
            <div>
              <Filter />
            </div>

            <div>
              {producerItemLists.map((item, index) => {
                return (
                  <CardItemPriducer
                    key={index}
                    waktu_panen={item.waktu_panen}
                    jenis_budidaya={item.jenis_budidaya}
                    user={item.user}
                    desc={item.desc}
                    title={item.title}
                  />
                );
              })}
            </div>
          </section>
        </Layout>
      </>
    </>
  );
}

export default FindProducerPage;
