import Head from "next/head";
import React from "react";
import { Layout, Navbar } from "~/components";
import Filter from "~/components/filters/Filter";
import { IFeedModel } from "../profile/utils/types";
import CardItemProducer from "./CardItemProducer";
import styles from "./FindProducer.module.scss";

function FindProducerPage({
  producerList,
  formik,
}: {
  producerList: IFeedModel[];
  formik: any;
}) {
  return (
    <>
      <>
        <Head>
          <title>Temukan Produsen | Lofiators</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <Layout classNames={styles.FindProducerPage}>
          <Navbar />

          <section className={styles.FindProducerPageContent}>
            <div>
              <Filter formik={formik} />
            </div>

            <div>
              {producerList.map((item, index) => {
                return (
                  <CardItemProducer
                    key={index}
                    title={item.title}
                    description={item.description}
                    harvest_time={item.harvest_time}
                    type_cultivation={item.type_cultivation}
                    user_name={item.user_name}
                    image={item.image}
                    id={item.id}
                    createdAt={item.createdAt}
                  />
                );
              })}
            </div>
          </section>
        </Layout>
      </>
    </>
  );
}

export default FindProducerPage;
