import React, { useEffect, useState } from "react";
import { Layout, Navbar } from "~/components";
import Head from "next/head";
import { authenticateRoute } from "~/lib/authenticate";
import { IUserModel } from "./utils/types";
import { fetchUserDetail } from "./utils/api";
import styles from "./ProfilePage.module.scss";
import ProfileUserCard from "./ProfileUserCard";

function ProfilePage() {
  const [user, setUser] = useState<IUserModel | null>(null);

  const fetchUser = async () => {
    try {
      const response = await fetchUserDetail();
      if (response.state) {
        setUser(response.data);
      }
    } catch (error) {
      setUser(null);
    }
  };

  useEffect(() => {
    fetchUser();
  }, []);

  return (
    <>
      <Head>
        <title>Profle | Lofiators</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <Layout classNames={styles.ProfilePage}>
        <section className={styles.ProfilePageContent}>
          <ProfileUserCard
            name={typeof user?.name !== "undefined" ? user.name : ""}
            city={typeof user?.city !== "undefined" ? user.city : ""}
            email={typeof user?.email !== "undefined" ? user.email : ""}
            image={typeof user?.image !== "undefined" ? user.image : ""}
            no_hp={typeof user?.no_hp !== "undefined" ? user.no_hp : ""}
          />
        </section>
      </Layout>
    </>
  );
}

export default authenticateRoute(ProfilePage);
