import React, { useEffect, useState } from "react";
import { Layout, Navbar } from "~/components";
import Head from "next/head";
import { authenticateRoute } from "~/lib/authenticate";
import { IUserModel } from "./utils/types";
import { fetchUserDetail } from "./utils/api";
import styles from "./ProfilePage.module.scss";
import ProfileUserCard from "./ProfileUserCard";
import FormUpdateProfile from "./FormUpdateProfile";

const initialUser: IUserModel = {
  name: "",
  city: "",
  no_hp: "",
  image: "",
  description: "",
  email: "",
};
function ProfilePage() {
  const [user, setUser] = useState<IUserModel>(initialUser);

  const fetchUser = async () => {
    try {
      const response = await fetchUserDetail();
      if (response.state) {
        setUser(response.data);
      }
    } catch (error) {
      setUser(initialUser);
    }
  };

  useEffect(() => {
    fetchUser();
  }, []);

  return (
    <>
      <Head>
        <title>Profle | Lofiators</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <Layout classNames={styles.ProfilePage}>
        <section className={styles.ProfilePageContent}>
          <ProfileUserCard
            name={user.name}
            city={user.city}
            email={user.email}
            image={user.image}
            no_hp={user.no_hp}
            description={user.description}
          />
        </section>
      </Layout>

      <FormUpdateProfile user={user} />
    </>
  );
}

export default authenticateRoute(ProfilePage);
