import Head from "next/head";
import React from "react";
import { Layout, Navbar } from "~/components";
import Filter from "~/components/filters/Filter";
import styles from "./FindCulvitator.module.scss";

function FindCulvitatorPage() {
  return (
    <>
      <>
        <Head>
          <title>Temukan Supplier | Lofiators</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <Layout classNames={styles.FindCulvitatorPage}>
          <Navbar />

          <section className={styles.FindCulvitatorPageContent}>
            <div>
              <Filter />
            </div>
          </section>
        </Layout>
      </>
    </>
  );
}

export default FindCulvitatorPage;
