import type { NextPage } from "next";
import Head from "next/head";
import { Layout, Navbar } from "~/components";
import DefaultButton from "~/components/button/DefaultButton";

import styles from "./HomePage.module.scss";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home | Lofiators</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <Navbar />

        <section className={styles.homepage}>
          <div>
            <h5>Segera perluas jangkauan pemasaran anda.</h5>
            <p className='w-3/4 mt-5 text-gray-500'>
              Bergabung bersama para pembudidaya dan supplier produk perikanan,
              dan temukan partner bisnis anda.
            </p>

            <div className='flex gap-2 mt-8'>
              <DefaultButton label='Cari Produsen' />
              <DefaultButton label='Cari Supplier' outline={true} />
            </div>
          </div>
          <div className={styles.image}></div>
        </section>
      </Layout>
    </>
  );
};

export default HomePage;
